### ISSUE TITLE
Not able to initialise a field  to default  on insert and increment the field on every update

### ISSUE THREAD

**Issue by sannip** [jtheisen/reconciler#10]
We have a UpdateCount integer field in our entity which is used to holds the count of entity updates. We need to initialise this field to 0 on insert but increment by 1 on every corresponding update. I tried to do it as shown below, but it did not work. This statement always initialized UpdateCount to 1 on insert. This might be because 'The OnUpdate definitions apply to insertions as well'.

```
            await _context.ReconcileAsync(entity,  e => e.WithMany(p => p.Details)              
                    .WithMany(p => p.Instructions)
                    .OnInsertion(p => p.Created == timeNow)
                    .OnInsertion(p => p.UpdateCount == 0)
                    .OnUpdate(p => p.LastUpdated == timeNow)
                    .OnUpdate(p => p.UpdateCount == p.UpdateCount + 1));
```

We do not any fields in our entity that could help us know if the particular entity is being updated/inserted. So, do you have any recommendations to handle this issue?

**Comment by jtheisen** [comment]
Well, one easy way would be to do the fix after the `Reconcile` call but before the `SaveChanges`.

But I will have a look why it doesn't work at some point also - I can at least say that I've never tested using the `p` on the right side of the `==` (only `new Guid()` and stuff like that).

**Comment by jtheisen** [comment]
Classing this as enhancement as I'm not yet sure how easily I can support this.

**Comment by sannip** [comment]
As per your suggestion, tried updating the entity before `SaveChanges`, but after `Reconcile`.
Noticed that `OnInsertion/OnUpdate` fields are not set in the entity after the reconcile call. They still are shown as the default DateTime.

```
            await _context.ReconcileAsync(entity,  e => e.WithMany(p => p.Details)              
                .WithMany(p => p.Instructions)
                .OnInsertion(p => p.Created == timeNow)
                .OnInsertion(p => p.UpdateCount == 0)
                .OnUpdate(p => p.LastUpdated == timeNow));

            if (entity.LastUpdated != entity.Created)
                entity.UpdateCount = entity.UpdateCount + 1;

            await _context.SaveChangesAsync();
```

**Comment by jtheisen** [comment]
Ok, that appears to be a bug then.

**Comment by jtheisen** [comment]
Looking at this after all these years I realized that this is likely not a bug, but a misunderstanding: The `entity` is the template and it's not modified. The changed data is returned as a new entity from the `Reconcile` call though.

Somewhat related, I just revised `OnInsertion` and `OnUpdate` after going through the open issues decided that `OnUpdate` can no longer operates on insertions, this now being changed as of version 1.2.0. The reason is that in cases where `OnUpdate` is used to use the existing value in the database (as is the case in this issue), it must have one and also ignore the given template value. `OnInsert` on the other hand, has only the template value and can never have a loaded one.
