### ISSUE TITLE
EF Core 3.0 Preview 3 and later: Scheduling of deletion now cascades before SaveChanges

### ISSUE THREAD

**Issue by cedwards-telis** [jtheisen/reconciler#5]
As far as I can tell new data is not inserted when using EF Core 3.0 Preview 8.

I cloned the package and all the tests passed.

I then upgraded the EF Core library and tests to .net standard 2.1 preview 8 and all the EF core dependencies to 3.0 preview 8.  Now two of the tests fail TestRemoveAndAddOne and TestRemoveAndAddOneWithNestedStuffAttached.

As much as I'd love to fix it and make a pull request I'm not sure I'm up to the task.  I've found the library very useful and I'm amazed at the low line count but I'm not finding it easy to see what's wrong.

**Comment by cedwards-telis** [comment]
The current stable version of ef core, 2.2.6 passes all tests.
ef core 3.0 Preview 1 passes all tests.
ef core 3.0 Preview 2 passes all tests.
ef core 3.0 Preview 3 and later fails the two indicated tests.

**Comment by jtheisen** [comment]
They appear to have changed the deletion behavior: In my test model, a person must have one address. So if the address is deleted, it's in principle correct to have the person also deleted. But in EFCore2 and EF6 this used to happen on the `SaveChanges` call, now (in the previews since 3) it happens right when you schedule the address for deletion. It won't give you the chance to fix the person's faulty address id afterwards. The person will already be scheduled for deletion also.

That's a breaking change on their part, and I wonder how aware they are of it. This is going to hit quite a few other people. I'll probably file a ticket there.

If they don't take it back, Reconciler will have to carefully change the person first, and only then, after it no longer depends on the to-be-deleted address, schedule that address for deletion.

What a nuisance.

Thanks for bringing this up, maybe it's not too late to make a fuzz.

**Comment by cedwards-telis** [comment]
Is it this issue?

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#cascade

**Comment by jtheisen** [comment]
Yes, thanks for finding that. Applying the configuration they mention makes the tests pass again ([see here](https://github.com/jtheisen/reconciler/commit/7400d0dcfeb338787a522b7572b5a5ec70c935cb)).

That looks as if complaining isn't much of an option.

At least there's a workaround now.

Should I come round to fixing this on my end, I'll post here again - I'll wait at least until EFCore3's release though.

**Comment by jtheisen** [comment]
Out of curiosity: What's your motivation to try preview versions? Is there a new feature you need in EFCore 3?

**Comment by cedwards-telis** [comment]
I'm using Server Side Blazor for a semi-experimental project which of course requires .net core 3.  The project isn't planned for release until after the likely release date of .net core 3.  Given that I was using .net core 3 I just sort of decided arbitrarily to do the API project in .net core 3 and ef core 3.

To be honest I haven't really noticed many feature improvements in ef core but perf is supposedly much better, it's a "changes under the hood" release.

This is interesting however - https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#notrackingresolution
https://github.com/aspnet/EntityFrameworkCore/issues/13518
